export * from "./country.entity";
export * from "./coverage.entity";
export * from "./fixtureCoverage.entity";
export * from "./league.entity";
export * from "./leagueFull.entity";
export * from "./leagueView.entity";
export * from "./countryView.entity";
export * from "./transfer.entity"
export * from "./leagueMatch.entity"
export * from "./match.entity"
export * from "./detailLeague.entity"
export * from "./teamTable.entity"
export * from "./infoLeague.entity"
export * from "./tableData.entity"
export * from "./team.entity"
export * from "./matchDetail.entity"
export * from "./events.entity"
export * from "./audio.entity"
export * from "./event.entity"